name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: yarn install

      - name: Build App
        run: yarn build:dev

      - name: Add SSH Key to Agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy App
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "rm -rf /opt/eth-lsd-app/out && mkdir -p /opt/eth-lsd-app/out && exit"
          rsync -r ./out/* ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/opt/eth-lsd-app/out
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "pm2 restart app && exit"
          echo "Deployment completed."
